jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          command: |
            apt update
            apt -y install \
              llvm-10-dev \
              libz-dev \
              build-essential \
              gcc-9 \
              g++-9 \
              git \
              make \
              cmake \
              libgtest-dev \
              python3-distutils \
              libfmt-dev \
              libboost-all-dev
          environment:
            DEBIAN_FRONTEND: noninteractive
      - run: mkdir build && cd build && cmake .. && make
      - run: cd build && ctest . --output-on-failure
