# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
workflows:
  default-workflow:
    jobs:
      - build:
          # for https://circleci.com/docs/2.0/private-images/
          context:
            - docker-hub-creds

jobs:
  build:
    docker:
      - image: insufficientlycaffeinated/bob:latest
        auth:
            # currently unused, but will be easy to set up if dockerhub starts blocking us
            username: $DOCKERHUB_USER
            password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: mkdir build && cd build && cmake .. && make
      - run: cd build && ctest . --output-on-failure
